baseurl          = "/"
title           = "Candidate"
languageCode    = "en-uk"
paginate        = "10"                                                                 # Number of posts per page
#theme           = "mainroad"
disqusShortname = ""                                                            # Enable comments by entering your Disqus shortname
googleAnalytics = ""                                                            # Enable Google Analytics by entering your tracking id

[Author]
    name = "John Doe"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"


[Params]
    gs_id           = "ab34c8"
    subtitle        = "Photobox Group Security - Candidate Site"                # Subtitle of your site
    description     = " John Doe's Personal blog about everything"              # Description of your site
    opengraph       = true
    readmore        = true                                                      # Show "Read more" button in list if true
    leftsidebar     = false                                                     # Move sidebar to the left side if true
    authorbox       = true
    post_navigation = true
    postSections    = ["post"]


[Params.widgets]
    search          = false
    recent_articles = true                              # Enable "Recent arcticles" widget
    categories      = false                             # Enable "Categories" widget
    tags            = false                             # Enable "Tags" widget
    tags_counter    = false                             # Enable counter for each tag in "Tags" widget (disabled by default)